# Generated by Django 5.1.3 on 2024-12-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='Hiredate',
        ),
    ]
