# Generated by Django 5.1.3 on 2024-12-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_rename_hire_date_employee_hiredate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Hiredate',
            new_name='hire_date',
        ),
    ]
